# Generated by Django 4.2.1 on 2023-06-02 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("final_project_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="train_ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("OriginStationID", models.CharField(default="N/A", max_length=100)),
                ("OriginStationName", models.JSONField(default=dict)),
                (
                    "DestinationStationID",
                    models.CharField(default="N/A", max_length=100),
                ),
                ("DestinationStationName", models.JSONField(default=dict)),
                ("Direction", models.BooleanField(default=-1)),
                ("Fares", models.JSONField(default=list)),
                ("UpdateTime", models.DateTimeField(default=None)),
                ("VersionID", models.BigIntegerField(default=-1)),
            ],
        ),
    ]
