# Generated by Django 4.2.1 on 2023-06-08 03:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "final_project_app",
            "0003_image_metro_thsr_thsrodfare_tra_traodfare_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="metro",
            old_name="DestinationStationID",
            new_name="DestinationStaionID",
        ),
    ]
