# Generated by Django 4.2.1 on 2023-06-08 06:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "final_project_app",
            "0004_rename_destinationstationid_metro_destinationstaionid",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="THSR_Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("UpdateTime", models.CharField(max_length=100)),
                ("EffectiveDate", models.CharField(max_length=100)),
                ("ExpiringDate", models.CharField(max_length=100)),
                ("VersionID", models.IntegerField()),
                ("TrainNo", models.CharField(max_length=10)),
                ("Direction", models.IntegerField()),
                ("StartingStationID", models.CharField(max_length=10)),
                ("StartingStationName_zh_tw", models.CharField(max_length=50)),
                ("StartingStationName_en", models.CharField(max_length=50)),
                ("EndingStationID", models.CharField(max_length=10)),
                ("EndingStationName_zh_tw", models.CharField(max_length=50)),
                ("EndingStationName_en", models.CharField(max_length=50)),
                ("StopSequence", models.IntegerField()),
                ("StationID", models.CharField(max_length=10)),
                ("StationName_zh_tw", models.CharField(max_length=50)),
                ("StationName_en", models.CharField(max_length=50)),
                ("ArrivalTime", models.TimeField(blank=True, null=True)),
                ("DepartureTime", models.TimeField(blank=True, null=True)),
                ("Monday", models.BooleanField()),
                ("Tuesday", models.BooleanField()),
                ("Wednesday", models.BooleanField()),
                ("Thursday", models.BooleanField()),
                ("Friday", models.BooleanField()),
                ("Saturday", models.BooleanField()),
                ("Sunday", models.BooleanField()),
                ("SrcUpdateTime", models.DateTimeField()),
            ],
        ),
    ]
