# Generated by Django 4.2.1 on 2023-06-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("final_project_app", "0006_remove_thsr_schedule_arrivaltime_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metro_sta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("StationID", models.CharField(max_length=100, null="N/A")),
                ("StationName_Zh_tw", models.CharField(max_length=100, null="N/A")),
            ],
        ),
    ]
