# Generated by Django 4.2.1 on 2023-06-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("final_project_app", "0007_metro_sta"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metro_sta_to_sta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("FromStationID", models.CharField(max_length=100, null="N/A")),
                ("FromStationName_Zh_tw", models.CharField(max_length=100, null="N/A")),
                ("ToStationID", models.CharField(max_length=100, null="N/A")),
                ("ToStationName_Zh_tw", models.CharField(max_length=100, null="N/A")),
                ("RunTime", models.IntegerField()),
                ("StopTime", models.IntegerField()),
            ],
        ),
    ]
